'use client';

import { ApiError } from '@naipay/api-client';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import { useEffect, useState, type FormEvent } from 'react';

import { AuthShell } from '@/components/auth/auth-shell';
import { RecoveryCodes } from '@/components/auth/recovery-codes';
import { Alert, Field } from '@/components/ui/field';
import { Button } from '@/components/ui/button';
import { api } from '@/lib/api';
import { useCurrentStaff } from '@/lib/auth/use-auth';

interface Enrolment {
  secret: string;
  otpauth_url: string;
  qr_code_svg: string;
}

/**
 * Two-factor enrolment.
 *
 * Mandatory for roles holding ledger, disbursement, access-control or identity
 * permissions — those accounts cannot use the console at all until this is
 * completed.
 *
 * Enrolment is two steps by design: a secret is issued, then proven. Activating
 * it on issue alone would lock out any operator whose authenticator failed to
 * scan.
 */
export default function TwoFactorEnrolPage() {
  const router = useRouter();
  const { data: staff } = useCurrentStaff();

  const [code, setCode] = useState('');
  const [recoveryCodes, setRecoveryCodes] = useState<string[] | null>(null);

  const begin = useMutation({
    mutationFn: () => api.post<Enrolment>('/admin/auth/two-factor/enrol'),
  });

  const confirm = useMutation({
    mutationFn: (input: { code: string }) =>
      api.post<{ recovery_codes: string[] }>('/admin/auth/two-factor/confirm', input),
    onSuccess: (data) => setRecoveryCodes(data.recovery_codes),
  });

  // Start enrolment as soon as the screen opens; there is nothing to show
  // until the server has issued a secret.
  useEffect(() => {
    begin.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const error = (begin.error ?? confirm.error) as ApiError | null;

  function handleConfirm(event: FormEvent) {
    event.preventDefault();
    confirm.mutate({ code });
  }

  if (recoveryCodes !== null) {
    return (
      <AuthShell
        title="Two-factor authentication is enabled"
        description="Save these recovery codes now. They are shown once and cannot be retrieved."
      >
        <RecoveryCodes codes={recoveryCodes} onContinue={() => router.replace('/')} />
      </AuthShell>
    );
  }

  return (
    <AuthShell
      title="Set up two-factor authentication"
      description={
        staff?.two_factor.required
          ? 'Your role requires two-factor authentication. Set it up to continue.'
          : 'Add a second factor to your Every Merchant account.'
      }
    >
      <div className="space-y-5">
        {error ? (
          <Alert tone="error" reference={error.correlationId}>
            {error.message}
          </Alert>
        ) : null}

        {begin.isPending ? (
          <p className="text-sm text-slate-500">Preparing your enrolment…</p>
        ) : null}

        {begin.data ? (
          <>
            <ol className="list-decimal space-y-1 pl-5 text-sm text-slate-600">
              <li>Open your authenticator app.</li>
              <li>Scan the code below, or enter the setup key by hand.</li>
              <li>Enter the six-digit code the app shows.</li>
            </ol>

            <div className="flex justify-center rounded-md border border-slate-200 bg-white p-4">
              {/*
                The QR is an SVG generated by the API from the otpauth URL, so
                the secret never travels to a third-party image service.
              */}
              <div
                aria-label="Two-factor QR code"
                dangerouslySetInnerHTML={{ __html: begin.data.qr_code_svg }}
              />
            </div>

            <div className="rounded-md bg-slate-50 p-3">
              <p className="text-xs font-medium text-slate-500">Setup key</p>
              <p className="numeric mt-1 text-sm break-all text-slate-800">{begin.data.secret}</p>
            </div>

            <form onSubmit={handleConfirm} className="space-y-4" noValidate>
              <Field
                label="Six-digit code"
                name="code"
                value={code}
                onChange={(event) => setCode(event.target.value)}
                inputMode="numeric"
                autoComplete="one-time-code"
                maxLength={6}
                required
                error={error?.fieldError('code')}
                className="numeric tracking-widest"
              />

              <Button type="submit" fullWidth loading={confirm.isPending}>
                Confirm and enable
              </Button>
            </form>
          </>
        ) : null}
      </div>
    </AuthShell>
  );
}
